### ISSUE TITLE
Configuration should not be ignored if there is an incompatibility

### ISSUE THREAD

**Issue by xeruf** [topgrade-rs/topgrade#607] opened 2023-11-12 18:20 UTC
## Erroneous Behavior
![image](https://github.com/topgrade-rs/topgrade/assets/13354331/48306712-622b-4dd3-9bda-eadf3b9270e0)

When something is found in the config that topgrade does not recognize, it ignores the config and plows on with the default, in my case for example running a self-update on Arch which is a no-go.
This poses multiple issues, especially for setups where different topgrade versions are used across different systems with the same config file (I use my dotfiles on Debian and Arch)

## Expected Behavior
Either exit altogether on parsing failure, or better yet ignore unrecognized keys (warn about them but not error out) so one can gracefully migrate.

## Steps to reproduce
Use an old config with the newest version.

See also https://github.com/r-darwish/topgrade/issues/847

**Comment by SteveLauC** [comment] 2023-11-13 01:51
Isn't this a duplicate of #491

**Comment by xeruf** [comment] 2024-02-28 01:40
yep it is, apparently I encounter this bug so often I sometimes don't even find my own report again ^^

**Comment by SteveLauC** [comment] 2024-02-28 01:44
Close as it is duplicate with #491

**Closed by SteveLauC** 2024-02-28 01:44 UTC
Labels: C-bug
