### ISSUE TITLE
Error while updating with paru/aur

### ISSUE THREAD

**Issue by uwussimo** [topgrade-rs/topgrade#239] opened 2022-11-29 17:25 UTC
## What did you expect to happen?
Upgrade the system using paru successfully.

## What actually happened?
Throws error...

## Additional Details
- Windows with Arch WSL
- scoop installed topgrade
- Topgrade 10.2.0

<details>
<pre>
―― (Arch) 22:19:43 - System update ―――――――――――――――――――――――――――――――――――――――――――――
no new news
System update failed:
   0: Command failed: `/usr/sbin/paru -Pw`
   1: `/usr/sbin/paru` failed: exit status: 1

Location:
   src/steps/os/archlinux.rs:34

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.ERROR
   0: Command failed: `/usr/sbin/notify-send -a Topgrade Topgrade 'System update failed'`

      Stderr:
      GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
   1: `/usr/sbin/notify-send` failed: exit status: 1

Location:
   src/terminal.rs:107

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
</pre>
</details>

**Comment by guihkx** [comment] 2022-11-29 22:40
Duplicate of #234

**Closed** 2022-11-30 06:53 UTC
