### ISSUE TITLE
Git step errors when current branch has no remote tracking branch set

### ISSUE THREAD

**Issue by underyx** [topgrade-rs/topgrade#69] opened 2022-10-24 18:39 UTC
## What did you expect to happen?

I ran the git step via topgrade targeting a repo where I recently created a local branch for some work in progress. This branch was never pushed to the remote. I expected topgrade to 1) fetch all other branches and 2) consider this branch up-to-date, as there can be no more recent refs for a branch that only exists locally.

## What actually happened?

Topgrade fails with an error, where git complains that my local branch has no tracking information.

```
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> bence/my-local-branch
```

## Additional Details

- Which operating system or Linux distribution are you using? macOS
- How did you install Topgrade? brew
- Which version are you running? Topgrade 9.0.1

**Comment by DottoDev** [comment] 2022-10-25 18:04
Can you try out this branch, if that's possible for you. https://github.com/DottoDev/topgrade-dev/tree/69-git-step-errors-when-current-branch-has-no-remote-tracking-branch-set

**Comment by pan93412** [comment] 2022-11-02 15:06
Seems duplicate of #86, which indicates that this issue has been fixed.

**Closed** 2022-11-02 15:09 UTC
