### ISSUE TITLE
summary of upgraded pkg

### ISSUE THREAD

**Issue by littleblack111** [topgrade-rs/topgrade#964] opened 2024-10-19 05:30 UTC
## I want to suggest a new step

* Which tool is this about? Where is its repository?
* Which operating systems are supported by this tool?
* What should Topgrade do to figure out if the tool needs to be invoked?
* Which exact commands should Topgrade run?
* Does it have a `--dry-run` option? i.e., print what should be done and exit
* Does it need the user to confirm the execution? And does it provide a `--yes`
  opation to skip this step?

## I want to suggest some general feature
Topgrade should add option to allow summary of what packages was upgraded

**Comment by Andreas02-dev** [comment] 2024-10-19 12:58
Duplicate of #943.

**Comment by SteveLauC** [comment] 2024-10-19 14:35
Close this issue as it is a duplication.

**Closed by SteveLauC** 2024-10-19 14:35 UTC
Labels: C-feature request
