### ISSUE TITLE
Add support for aura AUR helper

### ISSUE THREAD

**Issue by Abcd2591** [topgrade-rs/topgrade#35] opened 2022-10-18 15:41 UTC
### Which tool is this about? Where is its repository?
[aura](https://github.com/fosskers/aura) is an AUR helper and can be used for all regular pacman commands
### Which operating systems are supported by this tool?
Arch Linux and its derivatives
### What should Topgrade do to figure out if the tool needs to be invoked?
check if it is installed and the user has set arch_package_manager to aura
### Which exact commands should Topgrade run?
sudo aura -Akux (for aur packages)(this step has a hard dependency on sudo)
sudo aura -Syu (for pacman packages)

**Comment by DottoDev** [comment] 2022-10-22 18:13
Could you try out this branch: https://github.com/DottoDev/topgrade-dev/tree/35-add-support-for-aura-aur-helper

**Comment by Abcd2591** [comment] 2022-10-22 18:32
For the -Akux you need to use `sudo` for it to work, `doas` fails with an error (this will be fixed in aura 4.0).

Also the only thing required for aur update `-Au` there should be and `aura_arguments` option in the config to add other arguments like `-kx` (sorry for not putting this in the original issue)

**Comment by DottoDev** [comment] 2022-10-22 18:35
Will fix that

**Comment by DottoDev** [comment] 2022-10-22 20:07
Should be fixed new, reviewing it would be great

**Comment by Abcd2591** [comment] 2022-10-22 20:48
Its extremely broken

without setting `aura_pacman_arguments` to anything it gives me
```
Aura requires sudo installed to work with AUR packages
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config.rs:786:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After Setting aura_pacman_arguments to "" 

It says 
```
Aura requires sudo installed to work with AUR packages
``` 
and then does the package update.(I quadruple checked I have sudo and doas installed)

**Comment by DottoDev** [comment] 2022-10-22 21:02
Lul xD
I'll have a look tomorrow

**Comment by Abcd2591** [comment] 2022-10-22 21:04
Ok

Also I looked at the commits and understood almost nothing but you should change src/steps/os/archlinux.rs line 253 from `.arg("-Akux")` to `.arg("-Au")`

**Comment by DottoDev** [comment] 2022-10-22 21:05
Will do that

**Comment by DottoDev** [comment] 2022-10-23 08:36
Could you please try it out again. Aura should run two times, one time for AUR and one time for Pacman. aura for AUR should print a message if sudo is not installed.

**Comment by Abcd2591** [comment] 2022-10-23 09:19
If I have sudo and opendoas installed it only does the pacman update.
If I remove opendoas it does both steps

**Comment by DottoDev** [comment] 2022-10-23 09:49
Okay, thank you, i think the problem is that the sudo() command prefers doas over sudo. Will fix it. But it's great that everything else works

**Comment by DottoDev** [comment] 2022-10-23 16:19
Have changed a check for sudo now, if this doesn't work I will change the priorities of sudo/doas/etc, because currently its doas -> sudo -> gsudo -> pkexec.

**Comment by Abcd2591** [comment] 2022-10-23 16:34
It only does the AUR update with `assume_yes=true`
But it does both AUR and pacman updates completely fine with both sudo and opendoas installed when `assume_yes=true`

**Comment by DottoDev** [comment] 2022-10-23 17:56
At least better then before, xD

**Comment by DottoDev** [comment] 2022-10-23 17:59
Noticed why, put the commands in the wrong order. This will work now and support will be merged into the master branch.

**Comment by Abcd2591** [comment] 2022-10-23 18:03
Nice!

**Closed** 2022-10-23 18:07 UTC
Labels: request-package-manager, just-needs-check
