### ISSUE TITLE
Topgrade doesn't work with paru

### ISSUE THREAD

**Issue by eperulli** [topgrade-rs/topgrade#234] opened 2022-11-27 17:38 UTC
Topgrade doesn't perform any update and exits with code status 1
Screenshot follows

Steps to reproduce:
run topgrade with paru installed

![Screenshot_20221127_183303](https://user-images.githubusercontent.com/52085800/204150856-82c4264c-4727-41ab-b13c-bf67baa4bb36.png)

**Comment by guihkx** [comment] 2022-11-27 19:32
Thanks for reporting. It should be fixed by #235.

For now, as a workaround, you can prevent topgrade from checking for Arch Linux news by adding the following to `~/.config/topgrade.toml`:

```toml
[linux]
show_arch_news = false
```

**Comment by guihkx** [comment] 2022-11-27 22:24
Actually, @DottoDev already worked on a fix in #228.

Additionally, this is a duplicate of #220.

**Closed** 2022-12-08 17:24 UTC
