### ISSUE TITLE
Remote machines trying to contact remote machines despite being called remotely themselves

### ISSUE THREAD

**Issue by j-lakeman** [topgrade-rs/topgrade#786] opened 2024-05-04 14:36 UTC
## Erroneous Behavior
remote machines trying to contact themselves / other remote machines upon remote execution

## Expected Behavior
remote machines shouldnt "chain" but ignore remote machine entries in `topgrade.toml`

## Steps to reproduce

1. have a `topgrade.toml` with remote machines in it
2. have that same file on remote machine
3. run `topgrade` on host
4. remote machines trying to contact themselves / other remote machines

## Possible Cause (Optional)
`topgrade` doesn't check whether being invoked by another host

## Problem persists without calling from topgrade
- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [x] Yes
- [ ] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [x] Yes
- [ ] No

- Installation
Homebrew

- Topgrade version (`topgrade -V`)
Topgrade 14.0.1

**Comment by SteveLauC** [comment] 2024-05-18 08:08
> remote machines trying to contact themselves

So I guess in your configuration file, `remote_topgrades` has user specified, i.e., something like:

```toml
[misc]
remote_topgrades = ["user@host"]
```

If that is the case, yeah, this is bug and it has been fixed in #755 

-----

> remote machines trying to contact other remote machines upon remote execution

This is the expected behavior since they are specified in the configuration file.

**Closed** 2024-05-18 17:00 UTC
Labels: C-bug
